### ISSUE TITLE
GetCapabilities is broken

### ISSUE THREAD

**Issue by pmbohm** [aodn/geoserver-config#486]
### Whats happening
The XML from RC is not parsable. Geowebcache would not load layers with this response
http://geoserver-rc.aodn.org.au/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities

**Comment by jonescc** [comment]
Looks like an issue with the style for soop_co2_rt_trajectory_data

```
Caused by: javax.xml.transform.TransformerException: org.geoserver.platform.ServiceException: Error occurred trying to write out metadata for layer: soop_co2_rt_trajectory_data
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:749)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:353)
        at org.geotools.xml.transform.TransformerBase$Task.run(TransformerBase.java:300)
        at org.geotools.xml.transform.TransformerBase.transform(TransformerBase.java:133)
        at org.geotools.xml.transform.TransformerBase.transform(TransformerBase.java:112)
        at org.geoserver.wms.capabilities.GetCapabilitiesResponse.write(GetCapabilitiesResponse.java:114)
        ... 90 more
Caused by: org.geoserver.platform.ServiceException: Error occurred trying to write out metadata for layer: soop_co2_rt_trajectory_data
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleLayerTree(GetCapabilitiesTransformer.java:837)
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleLayers(GetCapabilitiesTransformer.java:714)
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleCapability(GetCapabilitiesTransformer.java:462)
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.encode(GetCapabilitiesTransformer.java:299)
        at org.geotools.xml.transform.TransformerBase$XMLReaderSupport.parse(TransformerBase.java:1026)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:671)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:740)
        ... 95 more
Caused by: java.lang.NullPointerException: Layer soop_co2_rt_trajectory_data has no default style
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleLayer(GetCapabilitiesTransformer.java:939)
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleLayerTree(GetCapabilitiesTransformer.java:826)
        ... 101 more
```

**Comment by bpasquer** [comment]
soop_co2_rt_trajectory_data style fixed by https://github.com/aodn/geoserver-config/pull/490

**Comment by jonescc** [comment]
Thanks @bpasquer !!
